### PR TITLE
feat(bonita): Add 7.3 documentation

### PR DESCRIPTION
**Pull request by tbouffard**
**WIP**
- rebase needed
- Needs doc content branch to be merged in bonita-doc or renamed

Remaining works
- convert notes, warnings, ...
- fix asciidoctor warnings

### CODE REVIEW

**Comment by tbouffard** [comment]
asciidoctor warnings, they may both come from bonita 7.3 and 7.5 and be caused by #54 

```log
asciidoctor: WARNING: skipping reference to missing attribute: security_opts
asciidoctor: ERROR: building-community-edition-from-source.adoc: line 32: invalid part, must have at least one section (e.g., chapter, appendix, etc.)
asciidoctor: ERROR: building-community-edition-from-source.adoc: line 39: invalid part, must have at least one section (e.g., chapter, appendix, etc.)
asciidoctor: WARNING: connector-development-toolkit.adoc: line 72: unterminated listing block
asciidoctor: WARNING: skipping reference to missing attribute: filter_name
asciidoctor: WARNING: enforce-password-policy.adoc: line 43: unterminated listing block
asciidoctor: WARNING: skipping reference to missing attribute: api_name
asciidoctor: WARNING: skipping reference to missing attribute: resource_name
asciidoctor: WARNING: skipping reference to missing attribute: api_name
asciidoctor: WARNING: skipping reference to missing attribute: resource_name
asciidoctor: WARNING: skipping reference to missing attribute: id
asciidoctor: WARNING: skipping reference to missing attribute: api_name
asciidoctor: WARNING: skipping reference to missing attribute: resource_name
asciidoctor: WARNING: skipping reference to missing attribute: id_part1
asciidoctor: WARNING: skipping reference to missing attribute: id_part2
asciidoctor: WARNING: skipping reference to missing attribute: api_name
asciidoctor: WARNING: skipping reference to missing attribute: resource_name
asciidoctor: WARNING: skipping reference to missing attribute: id
asciidoctor: WARNING: skipping reference to missing attribute: api_name
asciidoctor: WARNING: skipping reference to missing attribute: resource_name
asciidoctor: WARNING: skipping reference to missing attribute: id_part1
asciidoctor: WARNING: skipping reference to missing attribute: id_part2
asciidoctor: WARNING: skipping reference to missing attribute: api_name
asciidoctor: WARNING: skipping reference to missing attribute: resource_name
asciidoctor: WARNING: skipping reference to missing attribute: api_name
asciidoctor: WARNING: skipping reference to missing attribute: resource_name
asciidoctor: WARNING: skipping reference to missing attribute: page
asciidoctor: WARNING: skipping reference to missing attribute: count
asciidoctor: WARNING: skipping reference to missing attribute: order
asciidoctor: WARNING: skipping reference to missing attribute: query
asciidoctor: WARNING: skipping reference to missing attribute: filter_name
asciidoctor: WARNING: skipping reference to missing attribute: filter_value
asciidoctor: WARNING: ssl.adoc: line 40: unterminated listing block
asciidoctor: WARNING: skipping reference to missing attribute: security_opts
asciidoctor: ERROR: building-community-edition-from-source.adoc: line 39: invalid part, must have at least one section (e.g., chapter, appendix, etc.)
asciidoctor: WARNING: connector-development-toolkit.adoc: line 72: unterminated listing block
asciidoctor: WARNING: enforce-password-policy.adoc: line 43: unterminated listing block
asciidoctor: WARNING: event-handlers.adoc: line 28: section title out of sequence: expected level 1, got level 2
asciidoctor: WARNING: event-handlers.adoc: line 71: section title out of sequence: expected level 1, got level 2
asciidoctor: WARNING: event-handlers.adoc: line 130: section title out of sequence: expected level 1, got level 2
asciidoctor: WARNING: event-handlers.adoc: line 135: section title out of sequence: expected level 1, got level 2
asciidoctor: WARNING: event-handlers.adoc: line 165: section title out of sequence: expected level 1, got level 2
asciidoctor: WARNING: skipping reference to missing attribute: api_name
asciidoctor: WARNING: skipping reference to missing attribute: resource_name
asciidoctor: WARNING: skipping reference to missing attribute: api_name
asciidoctor: WARNING: skipping reference to missing attribute: resource_name
asciidoctor: WARNING: skipping reference to missing attribute: id
asciidoctor: WARNING: skipping reference to missing attribute: api_name
asciidoctor: WARNING: skipping reference to missing attribute: resource_name
asciidoctor: WARNING: skipping reference to missing attribute: id_part1
asciidoctor: WARNING: skipping reference to missing attribute: id_part2
asciidoctor: WARNING: skipping reference to missing attribute: api_name
asciidoctor: WARNING: skipping reference to missing attribute: resource_name
asciidoctor: WARNING: skipping reference to missing attribute: id
asciidoctor: WARNING: skipping reference to missing attribute: api_name
asciidoctor: WARNING: skipping reference to missing attribute: resource_name
asciidoctor: WARNING: skipping reference to missing attribute: id_part1
asciidoctor: WARNING: skipping reference to missing attribute: id_part2
asciidoctor: WARNING: skipping reference to missing attribute: api_name
asciidoctor: WARNING: skipping reference to missing attribute: resource_name
asciidoctor: WARNING: skipping reference to missing attribute: api_name
asciidoctor: WARNING: skipping reference to missing attribute: resource_name
asciidoctor: WARNING: skipping reference to missing attribute: page
asciidoctor: WARNING: skipping reference to missing attribute: count
asciidoctor: WARNING: skipping reference to missing attribute: order
asciidoctor: WARNING: skipping reference to missing attribute: query
asciidoctor: WARNING: skipping reference to missing attribute: filter_name
asciidoctor: WARNING: skipping reference to missing attribute: filter_value
asciidoctor: WARNING: ssl.adoc: line 36: unterminated listing block
asciidoctor: WARNING: tomcat-bundle.adoc: line 16: section title out of sequence: expected level 1, got level 2
asciidoctor: WARNING: tomcat-bundle.adoc: line 70: section title out of sequence: expected level 1, got level 2
asciidoctor: WARNING: tomcat-bundle.adoc: line 86: section title out of sequence: expected level 1, got level 2
asciidoctor: WARNING: tomcat-bundle.adoc: line 92: section title out of sequence: expected level 1, got level 2
asciidoctor: WARNING: tomcat-bundle.adoc: line 129: section title out of sequence: expected level 1, got level 2
```

**Comment by tbouffard** [comment]
Bonita 7.3 also has the #41 conversion issue

image

**Comment by tbouffard** [comment]
we have decided to push most of the content right now. The conversion issues will be manage later.

**Review by alachambre — APPROVED** [review]
Nice

**Pull request merged**
