### PR TITLE
feat: improve identification of preview environment and archive

### LINKED ISSUE #11: Start Migrating bonita-ici-doc content
The content of this [repository](https://github.com/bonitasoft/bonita-ici-doc) can be migrated right now
- we only want to keep a single version
- the documentation content will be based on the 1.3 version content and later adjusted incrementally

Tasks
- [x] create a `master` branch from 1.3 and migrate content, see https://github.com/bonitasoft/bonita-ici-doc/pull/118
- [x] integrate bici as part of the documentation site, see #17
- [x] setup GH workflow jobs in the bonita-ici-doc (covers #5), see https://github.com/bonitasoft/bonita-ici-doc/pull/119

**Note**
Once this is done, the content of the repository will be updated by content contributors.
This will
- let us validate the workflow
- let external non technical people use the solution
- allow to incrementally update the BICI doc content to be consistent with a single documentation version

### LINKED ISSUE #111: Improve identification of the "preview documentation content changes" environment
This is an improvement after #50 

Except with the url (something like `https://bonitasoft-bonita-ici-doc-build_preview-pr-124.surge.sh/bici/latest/`) and the page title (but it is not very visible in browser tab), we can not see at a first glance that we are looking as a preview doc content changes environment:

image

It will be nice to have a visual information like a different banner color and the component + pr number we are checking.
The title in the antora playbook used by the preview is set with this information, but we don't display the antora site title.
We could use it instead of the bonitasoft logo (at the top left of the page).
If possible, we should trigger this `preview mode` by setting a custom property/attribute in the antora playbook to make this explicit and avoid side effects in the future

### PR DESCRIPTION
**Pull request by tbouffard**
Use the non-production navbar:
  - dedicated title and background color
  - no search

The preview bash script now allows to
  - force usage of the production navbar
  - use locally built ui-bundle

The 'title' option has been renamed into 'site-title' for consistency

Depends on https://github.com/bonitasoft/bonita-documentation-theme/pull/37
Closes #111

### CODE REVIEW

**Comment by tbouffard** [comment]
Can be test locally by running
```bash
./build-preview.bash --ci false  --type local --branch master_asciidoctor --component cloud --pr 345  --fetch-sources false
```
Add ` --force-production-navbar true` if you want to see the regular navbar

image

**Comment by benjaminParisel** [comment]
👌

**Comment by tbouffard** [comment]
With a new version of the UI Bundle (display title + theme selector + manage mobile view)

image

**Review by benjaminParisel — APPROVED** [review]
Nice job 👏 👏

**Pull request merged**
